# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\about.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path

class Ui_aboutwindow(object):
    def setupUi(self, aboutwindow):
        aboutwindow.setObjectName("aboutwindow")
        aboutwindow.resize(360, 267)
        font = QtGui.QFont()
        font.setPointSize(10)
        aboutwindow.setFont(font)
        icon = QtGui.QIcon()

        #Added Path-definition as described in main file!
        icondir = Path(__file__).absolute().parent

        icon.addPixmap(QtGui.QPixmap(str(icondir / 'img/isrt.ico')), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        aboutwindow.setWindowIcon(icon)
        self.aboutbody = QtWidgets.QLabel(aboutwindow)
        self.aboutbody.setGeometry(QtCore.QRect(20, 10, 321, 191))
        self.aboutbody.setObjectName("aboutbody")
        self.pushButton = QtWidgets.QPushButton(aboutwindow)
        self.pushButton.setGeometry(QtCore.QRect(150, 210, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(aboutwindow)
        QtCore.QMetaObject.connectSlotsByName(aboutwindow)

    def retranslateUi(self, aboutwindow):
        _translate = QtCore.QCoreApplication.translate
        aboutwindow.setWindowTitle(_translate("aboutwindow", "About ISRT"))
        self.aboutbody.setText(_translate("aboutwindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">ISRT v0.1</span></p><p align=\"center\"><span style=\" font-size:10pt;\">Insurgency Sandstorm RCON Tool</span></p><p align=\"center\">Created by Madman/Sargolin</p><p align=\"center\">Support: oe@edelmeier.org</p><p align=\"center\">GitHub:</p><p align=\"center\"><a href=\"https://github.com/sargolin/ISRT-Insurgency-Sandstorm-RCON-TOOL-and-Mapchanger\"><span style=\" font-size:6pt; text-decoration: underline; color:#0000ff;\">https://github.com/sargolin/ISRT-Insurgency-Sandstorm-RCON-TOOL-and-Mapchanger</span></a></p></body></html>"))
        self.pushButton.setText(_translate("aboutwindow", "Close"))
