# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\about_gui_v0.3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path
icondir = Path(__file__).absolute().parent

class Ui_aboutwindow(object):
    def setupUi(self, aboutwindow):
        aboutwindow.setObjectName("aboutwindow")
        aboutwindow.resize(360, 267)
        font = QtGui.QFont()
        font.setPointSize(10)
        aboutwindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(icondir / 'img/isrt.ico')), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        aboutwindow.setWindowIcon(icon)
        self.aboutbody = QtWidgets.QLabel(aboutwindow)
        self.aboutbody.setGeometry(QtCore.QRect(20, 10, 321, 191))
        self.aboutbody.setObjectName("aboutbody")
        self.pushButton = QtWidgets.QPushButton(aboutwindow)
        self.pushButton.setGeometry(QtCore.QRect(150, 210, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(aboutwindow)
        QtCore.QMetaObject.connectSlotsByName(aboutwindow)

    def retranslateUi(self, aboutwindow):
        _translate = QtCore.QCoreApplication.translate
        aboutwindow.setWindowTitle(_translate("aboutwindow", "About ISRT"))
        self.aboutbody.setText(_translate("aboutwindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">ISRT v0.3</span></p><p align=\"center\">Insurgency Sandstorm RCON/Query Tool</p><p align=\"center\">Created by Madman</p><p align=\"center\">Support: <a href=\"mailto:isrt@edelmeier.org\"><span style=\" text-decoration: underline; color:#0000ff;\">isrt@edelmeier.org</span></a></p><p align=\"center\"><a href=\"https://github.com/sargolin/ISRT-Insurgency-Sandstorm-RCON-TOOL-and-Mapchanger\"><span style=\" text-decoration: underline; color:#0000ff;\">GitHub</span></a></p><p align=\"center\">GNU/Public License Software </p></body></html>"))
        self.pushButton.setText(_translate("aboutwindow", "Close"))
