# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\help_gui_v0.3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path
icondir = Path(__file__).absolute().parent

class Ui_helpwindow(object):
    def setupUi(self, helpwindow):
        helpwindow.setObjectName("helpwindow")
        helpwindow.resize(430, 590)
        helpwindow.setMinimumSize(QtCore.QSize(430, 590))
        helpwindow.setMaximumSize(QtCore.QSize(430, 590))
        font = QtGui.QFont()
        font.setPointSize(10)
        helpwindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\img/isrt.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        helpwindow.setWindowIcon(icon)
        self.helpbody = QtWidgets.QLabel(helpwindow)
        self.helpbody.setGeometry(QtCore.QRect(20, 10, 411, 531))
        self.helpbody.setObjectName("helpbody")
        self.pushButton = QtWidgets.QPushButton(helpwindow)
        self.pushButton.setGeometry(QtCore.QRect(190, 550, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(helpwindow)
        QtCore.QMetaObject.connectSlotsByName(helpwindow)

    def retranslateUi(self, helpwindow):
        _translate = QtCore.QCoreApplication.translate
        helpwindow.setWindowTitle(_translate("helpwindow", "RCON Help ISRT"))
        self.helpbody.setText(_translate("helpwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">RCON Help</span></p>\n"
"\n"
"\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>help</b></i>&nbsp;&nbsp;&nbsp;  Displays a list of commands.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>listplayers </b></i>&nbsp;&nbsp;&nbsp;Lists players currently connected to the server.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>kick &lt;id/netid/name&gt; [reason]</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Kicks a player from the server.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>permban &lt;id/netid/name&gt; [reason]</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Permanently bans a player from the server.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>travel &lt;travel url&gt;</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Transitions the server to a different level.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>ban &lt;id/netid/name&gt; [duration in minutes] [reason]</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bans a player from the server.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>banid &lt;netid&gt; [duration in minutes] [reason]</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bans a player by net ID from the server.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>listbans </b></i>&nbsp;&nbsp;&nbsp;Shows the ban list for the server.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>unban &lt;netid&gt; Lifts a ban for a user.</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>say &lt;message&gt; </b></i>&nbsp;&nbsp;&nbsp;Shows a message to all players in the chat box.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>restartround [0 = no team switch, 1 = swap teams]</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Restarts the current round.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>maps [level filter]</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lists available maps.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>scenarios [level filter]</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lists available scenarios.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>travelscenario &lt;scenario&gt;</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Change level to given scenario.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>gamemodeproperty &lt;property&gt; [new value]</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Gets or sets a gamemode property for the length of the scenario.</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><i><b>listgamemodeproperties [property filter]</p></b></i>&nbsp;&nbsp;&nbsp;\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lists available gamemode properties for the current gamemode.</p></body></html>"))
        self.pushButton.setText(_translate("helpwindow", "Close"))
