# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\source_files\histmgr_gui_v0.6.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_histmgr_window(object):
    def setupUi(self, histmgr_window):
        histmgr_window.setObjectName("histmgr_window")
        histmgr_window.resize(588, 556)
        histmgr_window.setMinimumSize(QtCore.QSize(0, 0))
        histmgr_window.setMaximumSize(QtCore.QSize(2500, 1440))
        font = QtGui.QFont()
        font.setPointSize(10)
        histmgr_window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\img/isrt.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        histmgr_window.setWindowIcon(icon)
        self.btn_histmgr_close = QtWidgets.QPushButton(histmgr_window)
        self.btn_histmgr_close.setGeometry(QtCore.QRect(270, 520, 75, 23))
        self.btn_histmgr_close.setStyleSheet("background-color:rgb(228, 228, 228)\n"
"")
        self.btn_histmgr_close.setObjectName("btn_histmgr_close")

        self.retranslateUi(histmgr_window)
        QtCore.QMetaObject.connectSlotsByName(histmgr_window)

    def retranslateUi(self, histmgr_window):
        _translate = QtCore.QCoreApplication.translate
        histmgr_window.setWindowTitle(_translate("histmgr_window", "RCON Command History Manager"))
        histmgr_window.setToolTip(_translate("histmgr_window", "Command History Manager"))
        histmgr_window.setStatusTip(_translate("histmgr_window", "Command History Manager"))
        self.btn_histmgr_close.setText(_translate("histmgr_window", "Close"))
