# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\server_gui_v0.4.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_server_window(object):
    def setupUi(self, server_window):
        server_window.setObjectName("server_window")
        server_window.resize(571, 151)
        server_window.setMinimumSize(QtCore.QSize(571, 151))
        server_window.setMaximumSize(QtCore.QSize(571, 151))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\img/isrt.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        server_window.setWindowIcon(icon)
        self.layoutWidget = QtWidgets.QWidget(server_window)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 554, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.server_alias = QtWidgets.QLineEdit(self.layoutWidget)
        self.server_alias.setText("")
        self.server_alias.setObjectName("server_alias")
        self.horizontalLayout.addWidget(self.server_alias)
        self.server_ip = QtWidgets.QLineEdit(self.layoutWidget)
        self.server_ip.setText("")
        self.server_ip.setObjectName("server_ip")
        self.horizontalLayout.addWidget(self.server_ip)
        self.server_query = QtWidgets.QLineEdit(self.layoutWidget)
        self.server_query.setText("")
        self.server_query.setObjectName("server_query")
        self.horizontalLayout.addWidget(self.server_query)
        self.server_rconport = QtWidgets.QLineEdit(self.layoutWidget)
        self.server_rconport.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.server_rconport.setText("")
        self.server_rconport.setObjectName("server_rconport")
        self.horizontalLayout.addWidget(self.server_rconport)
        self.server_rconpw = QtWidgets.QLineEdit(self.layoutWidget)
        self.server_rconpw.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.server_rconpw.setText("")
        self.server_rconpw.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.server_rconpw.setObjectName("server_rconpw")
        self.horizontalLayout.addWidget(self.server_rconpw)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_server_add = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_server_add.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_server_add.setObjectName("btn_server_add")
        self.horizontalLayout_2.addWidget(self.btn_server_add)
        self.btn_server_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_server_delete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_server_delete.setObjectName("btn_server_delete")
        self.horizontalLayout_2.addWidget(self.btn_server_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.dropdown_server_list = QtWidgets.QComboBox(self.layoutWidget)
        self.dropdown_server_list.setStyleSheet("background-color: rgb(240, 240, 240)")
        self.dropdown_server_list.setEditable(True)
        self.dropdown_server_list.setObjectName("dropdown_server_list")
        self.verticalLayout.addWidget(self.dropdown_server_list)
        self.label_db_console = QtWidgets.QTextEdit(server_window)
        self.label_db_console.setGeometry(QtCore.QRect(9, 100, 554, 41))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_db_console.setFont(font)
        self.label_db_console.setAutoFillBackground(False)
        self.label_db_console.setStyleSheet("background-color: rgb(240, 240, 240)")
        self.label_db_console.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_db_console.setReadOnly(False)
        self.label_db_console.setObjectName("label_db_console")

        self.retranslateUi(server_window)
        QtCore.QMetaObject.connectSlotsByName(server_window)

    def retranslateUi(self, server_window):
        _translate = QtCore.QCoreApplication.translate
        server_window.setWindowTitle(_translate("server_window", "ISRT Server Management"))
        self.server_alias.setStatusTip(_translate("server_window", "Alias Name of the server"))
        self.server_alias.setPlaceholderText(_translate("server_window", "Your Alias"))
        self.server_ip.setStatusTip(_translate("server_window", "IP Address of the server"))
        self.server_ip.setPlaceholderText(_translate("server_window", "IP-Address"))
        self.server_query.setStatusTip(_translate("server_window", "Query Port of the server"))
        self.server_query.setPlaceholderText(_translate("server_window", "Query Port"))
        self.server_rconport.setStatusTip(_translate("server_window", "RCON Port of the server"))
        self.server_rconport.setPlaceholderText(_translate("server_window", "RCON Port"))
        self.server_rconpw.setStatusTip(_translate("server_window", "RCON Password of the server"))
        self.server_rconpw.setPlaceholderText(_translate("server_window", "RCON Password"))
        self.btn_server_add.setStatusTip(_translate("server_window", "Execute a query command to the defined server"))
        self.btn_server_add.setText(_translate("server_window", "Add Server"))
        self.btn_server_delete.setStatusTip(_translate("server_window", "Execute a query command to the defined server"))
        self.btn_server_delete.setText(_translate("server_window", "Delete Server"))
        self.dropdown_server_list.setToolTip(_translate("server_window", "Select Server to modify/delete from List"))
        self.dropdown_server_list.setStatusTip(_translate("server_window", "Select Server to modify/delete from List"))
        self.dropdown_server_list.setCurrentText(_translate("server_window", "Select Server to modify/delete from List"))
        self.dropdown_server_list.setPlaceholderText(_translate("server_window", "Select Server"))
        self.label_db_console.setToolTip(_translate("server_window", "DB Console"))
        self.label_db_console.setHtml(_translate("server_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_db_console.setPlaceholderText(_translate("server_window", "Database connection output console"))
